/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.paciente;

import dao.DaoPaciente;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Paciente;

/**
 *
 * @author Ronaldo
 */
public class PesquisaPaciente extends javax.swing.JDialog {

    /**
     * Creates new form Teste
     */
    private static Paciente pacienteSelecionado;
    private DaoPaciente daoPaciente;
    
    public static Paciente buscaPaciente(JFrame parent){
        PesquisaPaciente pesquisaPaciente = new PesquisaPaciente(parent, true);
        pesquisaPaciente.show();
        return pacienteSelecionado;
    }
    
    public void pesquisar(){
        if (!TextPesquisa.getText().equals("")){
            List<Paciente> lista = new ArrayList<Paciente>();
            if (radioNome.isSelected()){
                lista = daoPaciente.listarPorNome(TextPesquisa.getText());
            }else if (radioCPF.isSelected()){
                lista = daoPaciente.listarPorCPF(TextPesquisa.getText());
            }else if (radioRG.isSelected()){
                lista = daoPaciente.listarPorRG(TextPesquisa.getText());
            }
            
            Collections.sort(lista);
            DefaultTableModel tableModel = (DefaultTableModel) tableBusca.getModel();
            tableModel.setNumRows(0);
            for(Paciente p: lista){
                 tableModel.addRow(new String[]{
                     p.getId().toString(),
                     p.getNome(),
                     p.getRg()!=null?p.getRg():"",
                     p.getCpf()!=null?p.getCpf():""
                 });
             }            
        }
    }
    
    public PesquisaPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TextPesquisa.requestFocus();
        try{
            daoPaciente = new DaoPaciente();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Problema de conexão!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        radioNome = new javax.swing.JRadioButton();
        radioCPF = new javax.swing.JRadioButton();
        radioRG = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBusca = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Pacientes");
        setBackground(new java.awt.Color(206, 234, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        TextPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextPesquisaKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        radioNome.setBackground(new java.awt.Color(0, 204, 204));
        radioNome.setSelected(true);
        radioNome.setText("Nome");
        radioNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNomeActionPerformed(evt);
            }
        });

        radioCPF.setBackground(new java.awt.Color(0, 204, 204));
        radioCPF.setText("CPF");
        radioCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCPFActionPerformed(evt);
            }
        });

        radioRG.setBackground(new java.awt.Color(0, 204, 204));
        radioRG.setText("RG");
        radioRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radioNome)
                        .addGap(18, 18, 18)
                        .addComponent(radioCPF)
                        .addGap(18, 18, 18)
                        .addComponent(radioRG)
                        .addGap(0, 374, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNome)
                    .addComponent(radioCPF)
                    .addComponent(radioRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextPesquisa))
                .addContainerGap())
        );

        tableBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "RG", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBuscaMouseClicked(evt);
            }
        });
        tableBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableBuscaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableBusca);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextPesquisaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER){
            pesquisar();
        }
    }//GEN-LAST:event_TextPesquisaKeyPressed

    private void tableBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableBuscaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableBuscaKeyPressed

    private void tableBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBuscaMouseClicked
        if (evt.getClickCount() == 2){
            long codPaciente = Long.parseLong(tableBusca.getValueAt(tableBusca.getSelectedRow(), 0).toString());
            Paciente p = daoPaciente.getById(codPaciente);
            this.pacienteSelecionado = p;
            dispose();
        }
    }//GEN-LAST:event_tableBuscaMouseClicked

    private void radioNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNomeActionPerformed
        TextPesquisa.requestFocus();
    }//GEN-LAST:event_radioNomeActionPerformed

    private void radioCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCPFActionPerformed
        TextPesquisa.requestFocus();
    }//GEN-LAST:event_radioCPFActionPerformed

    private void radioRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRGActionPerformed
        TextPesquisa.requestFocus();
    }//GEN-LAST:event_radioRGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisaPaciente dialog = new PesquisaPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCPF;
    private javax.swing.JRadioButton radioNome;
    private javax.swing.JRadioButton radioRG;
    private javax.swing.JTable tableBusca;
    // End of variables declaration//GEN-END:variables

}
